FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist/frontend /app/dist/frontend
COPY --from=build /app/node_modules /app/node_modules
EXPOSE 4000
CMD ["node", "/app/dist/frontend/server/server.mjs"]